apiVersion: gravitee.io/v1alpha1
kind: ApiV4Definition
metadata:
  name: drinks-api
spec:
  name: "Drinks API"
  contextRef: 
    name: context
  description: "An API for ordering pizza"
  version: "1.0"
  type: PROXY
  listeners:
    - type: HTTP
      paths:
        - path: "/drinks"
      entrypoints:
        - type: http-proxy
          qos: AUTO
  endpointGroups:
    - name: Default HTTP proxy group
      type: http-proxy
      endpoints:
        - name: Default HTTP proxy
          type: http-proxy
          inheritConfiguration: false
          configuration:
            target: https://api.gravitee.io/echo
          secondary: false
  flowExecution:
    mode: DEFAULT
    matchRequired: false
  plans:
    API_KEY:
      name: "Keyless plan"
      security:
        type: "KEY_LESS"